djangoecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

from django.conf.urls import url
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^',  include("djangoecommerce_web.urls")),
    url(r'^musteri/', include("djangoecommerce_customer.urls")),
    url(r'^sirket/', include("djangoecommerce_company.urls")),
    url(r'^blog/', include("djangoecommerce_blog.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoecommerce_blog/urls.py
from django.conf.urls import url
from djangoecommerce_blog.views import CategoryListView, BlogListView, BlogDetailView,HashtagListView


app_name = 'djangoecommerce_blog'


urlpatterns = [
    url(r'^$', BlogListView, name='homepage'),
    url(r'^(?P<slug>[-\w]+)/$',BlogDetailView, name='blog_single'),
    url(r'^category/(?P<category_slug>[-\w]+)/$',CategoryListView, name='category_all'),
    url(r'^hashtag/(?P<hashtag>[-\w]+)/$',HashtagListView, name='hashtag'),
]

djangoecommerce_web/urls.py
from django.conf.urls import url

from djangoecommerce_web.views import IndexView, ProductDetailView, BlogDetailView,ContactView

app_name = 'djangoecommerce_web'

urlpatterns = [
    url(r'^$', IndexView, name='homepage'),
    url(r'^urun/(?P<id>[-\w]+)/$',ProductDetailView, name='product_detail'),
    url(r'^contact/$', ContactView, name='contact'),
]

djangoecommerce_web/forms.py
from django import forms
from django.forms import ModelForm, TextInput
from djangoecommerce_app.models import Contact

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ["name", "email", "subject", "message"]
        widgets = {
            'name': TextInput(attrs={'id': 'input_name','class':'form_input input_name input_ph', 'name': 'your-name', 'placeholder':'Name','data-error':'Name is required'}),
            'email': TextInput(attrs={'id': 'input_email','class':'form_input input_email input_ph', 'name': 'your-email', 'placeholder':'Email','data-error':'Valid email is required.'}),
            'subject': TextInput(attrs={'id': 'subject','class':'form_input input_name input_ph', 'name': 'your-subject', 'placeholder':'Subject','data-error':'Name is required'}),
            'message': TextInput(attrs={'id': 'subject','class':'input_ph input_message', 'name': 'your-message', 'placeholder':'Message','data-error':'Please, write us a message'}),
}

djangoecommerce_web/views.py
from django.shortcuts import render, redirect
from djangoecommerce_app.models import User, City, CompanyAddress, CompanyFeature,Card,Order, Company, ProductCategory,  Product, ProductImage, ProductBrand, Contact
from djangoecommerce_blog.models import Blog
from djangoecommerce_web.forms import ContactForm

def IndexView(request):
    context={
        "blog":Blog.objects.all()[:3],
        "product":Product.objects.all()
    }
    return render(request, 'web/index.html',context)


def ProductDetailView(request,id):
    context = {
        "product":Product.objects.get(id=id),
    }
    return render(request, 'web/product/product-detail.html',context)


def BlogDetailView(request,slug):
    context = {
        "blog":Blog.objects.get(slug=slug),
    }
    return render(request, 'web/blog-single.html',context)


def ContactView(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        Contact = form.save(commit=True)
        return redirect("djangoecommerce_web:contact")
    context = {
        "form": form
    }
    return render(request, 'web/contact.html',context)

djangoecommerce_web/templates/web/components/footer.html
{% load static %}
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <div class="footer_nav_container d-flex flex-sm-row flex-column align-items-center justify-content-lg-start justify-content-center text-center">
          <ul class="footer_nav">
            <li><a href="#">Blog</a></li>
            <li><a href="#">FAQs</a></li>
            <li><a href="contact.html">Contact us</a></li>
          </ul>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="footer_social d-flex flex-row align-items-center justify-content-lg-end justify-content-center">
          <ul>
            <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
            <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
            <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
            <li><a href="#"><i class="fa fa-skype" aria-hidden="true"></i></a></li>
            <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div class="footer_nav_container">
          <div class="cr">©2018 All Rights Reserverd.</div>
        </div>
      </div>
    </div>
  </div>
</footer>

djangoecommerce_web/templates/web/components/header.html
{% load static %}
<div class="fs_menu_overlay"></div>
<div class="hamburger_menu">
  <div class="hamburger_close"><i class="fa fa-times" aria-hidden="true"></i></div>
  <div class="hamburger_menu_content text-right">
    <ul class="menu_top_nav">
      <li class="menu_item has-children">
        <a href="#">
          usd
          <i class="fa fa-angle-down"></i>
        </a>
        <ul class="menu_selection">
          <li><a href="#">cad</a></li>
          <li><a href="#">aud</a></li>
          <li><a href="#">eur</a></li>
          <li><a href="#">gbp</a></li>
        </ul>
      </li>
      <li class="menu_item has-children">
        <a href="#">
          English
          <i class="fa fa-angle-down"></i>
        </a>
        <ul class="menu_selection">
          <li><a href="#">French</a></li>
          <li><a href="#">Italian</a></li>
          <li><a href="#">German</a></li>
          <li><a href="#">Spanish</a></li>
        </ul>
      </li>
      <li class="menu_item has-children">
        <a href="#">
          My Account
          <i class="fa fa-angle-down"></i>
        </a>
        <ul class="menu_selection">
          <li><a href="#"><i class="fa fa-sign-in" aria-hidden="true"></i>Sign In</a></li>
          <li><a href="#"><i class="fa fa-user-plus" aria-hidden="true"></i>Register</a></li>
        </ul>
      </li>
      <li class="menu_item"><a href="{% url 'djangoecommerce_web:homepage' %}">home</a></li>
      <li class="menu_item"><a href="#">shop</a></li>
      <li class="menu_item"><a href="#">promotion</a></li>
      <li class="menu_item"><a href="#">pages</a></li>
      <li class="menu_item"><a href="{% url 'djangoecommerce_blog:homepage' %}">blog</a></li>
      <li class="menu_item"><a href="#">contact</a></li>
    </ul>
  </div>
</div>

djangoecommerce_web/templates/web/components/main_navigation.html
{% load static %}
<div class="main_nav_container">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-right">
        <div class="logo_container">
          <a href="{% url 'djangoecommerce_web:homepage' %}"><img src="{% static 'web/images/logo.png' %}" alt=""></a>
        </div>
        <nav class="navbar">
          <ul class="navbar_menu">
            <li><a href="{% url 'djangoecommerce_web:homepage' %}">home</a></li>
            <li><a href="#">shop</a></li>
            <li><a href="{% url 'djangoecommerce_blog:homepage' %}">blog</a></li>
            <li><a href="{% url 'djangoecommerce_web:contact' %}">contact</a></li>
          </ul>
          <ul class="navbar_user">
            <li><a href="#"><i class="fa fa-search" aria-hidden="true"></i></a></li>
            <li><a href="#"><i class="fa fa-user" aria-hidden="true"></i></a></li>
            <li class="checkout">
              <a href="#">
                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                <span id="checkout_items" class="checkout_items">2</span>
              </a>
            </li>
          </ul>
          <div class="hamburger_container">
            <i class="fa fa-bars" aria-hidden="true"></i>
          </div>
        </nav>
      </div>
    </div>
  </div>
</div>

djangoecommerce_web/templates/web/components/top_navigation.html
<div class="top_nav">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="top_nav_left">free shipping on all u.s orders over $50</div>
      </div>
      <div class="col-md-6 text-right">
        <div class="top_nav_right">
          <ul class="top_nav_menu">

            <!-- Currency / Language / My Account -->

            <li class="currency">
              <a href="#">
                tl
                <i class="fa fa-angle-down"></i>
              </a>
              <ul class="currency_selection">
                <li><a href="#">usd</a></li>
              </ul>
            </li>
            <li class="language">
              <a href="#">
                Türkçe
                <i class="fa fa-angle-down"></i>
              </a>
              <ul class="language_selection">
                <li><a href="#">English</a></li>
                <li><a href="#">Italian</a></li>
                <li><a href="#">German</a></li>
                <li><a href="#">Spanish</a></li>
              </ul>
            </li>
            <li class="account">
              <a href="#">
                Giriş Yap
                <i class="fa fa-angle-down"></i>
              </a>
              <ul class="account_selection">
                <li><a href="#"><i class="fa fa-sign-in" aria-hidden="true"></i>Giriş Yap</a></li>
                <li><a href="#"><i class="fa fa-user-plus" aria-hidden="true"></i>Kullanıcı Oluştur</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>